server:
  port: 8000

eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka

spring:
  application:
    name: gateway-service
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://i6c109.p.ssafy.io:3306/CAMP?serverTimezone=Asia/Seoul
    username: root
    password: qorrn1!
    
  jpa:
    hibernate:
      ddl-auto: none #create update none
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    show-sql: true
  cloud:
   gateway:
     globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: "*"
            allow-credentials: true
            allowedMethods: "*"
            allowedHeaders: "*"
            exposedHeaders: "*"
     routes:           
      - id: auth-service
        uri: lb://AUTH-SERVICE # 포워딩할 주소 http://localhost:8000/oauth 로 들어오면 http://localhost:8050으로 포워딩
        predicates:
          - Path=/oauth/** # 해당 gateway 서버의 /oauth/**로 들어오는 요은 auth-service로 인식하겠다는 조건
              
      - id: auth-service
        uri: lb://AUTH-SERVICE
        predicates:
          - Path=/user/**
              
      - id: auth-service
        uri: lb://AUTH-SERVICE
        predicates:
          - Path=/follow/**
        filters:
          - CustomFilter
          
      - id: chat-service
        uri: lb://CHAT-SERVICE
        predicates:
          - Path=/chat/**
        filters:
          - CustomFilter
          
      - id: chat-service
        uri: lb://CHAT-SERVICE
        predicates:
          - Path=/stomp/**
        filters:
          - CustomFilter
          
      - id: chat-service
        uri: lb://CHAT-SERVICE
        predicates:
          - Path=/sub/**
        filters:
          - CustomFilter
          
      - id: chat-service
        uri: lb://CHAT-SERVICE
        predicates:
          - Path=/pub/**
        filters:
          - CustomFilter
              
      - id: board-service
        uri: lb://BOARD-SERVICE
        predicates:
          - Path=/board/**
        filters:
          - CustomFilter
          
      - id: board-service
        uri: lb://BOARD-SERVICE
        predicates:
          - Path=/like/**
        filters:
          - CustomFilter
          
      - id: board-service
        uri: lb://BOARD-SERVICE
        predicates:
          - Path=/comment/**
        filters:
          - CustomFilter
          
      - id: camp-service
        uri: lb://CAMP-SERVICE
        predicates:
          - Path=/camp/**
        filters:
          - CustomFilter